# Generated by Django 2.1.3 on 2018-12-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0002_auto_20181203_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(choices=[('0', '校长'), ('1', '教师'), ('2', '学生')], default=2, max_length=10),
        ),
    ]
